target1: prerequisite1 prerequisite2
	# target name
	echo $@
	# prerequisites newer than the target
	echo $?
	# all prerequisites  
	echo $^


prerequisite1:
	echo "prerequisite1"

prerequisite2:
	echo "prerequisite2"
