all: position-arguments getopts

position-arguments:
	echo "run position-arguments.sh"
	chmod a+x position-arguments.sh
	./position-arguments.sh a2htray male student

getopts:
	echo "run getopts.sh"
	chmod a+x getopts.sh
	./getopts.sh -r student -g male -u a2htray
